# Data configuration
data:
  snp_data_path: "data/processed/snp_data.npy"
  trait_data_path: "data/processed/trait_data.npy"
  train_ratio: 0.7

# Model configuration
model:
  input_dim: 4000
  encoding_dim: 1000
  num_heads: 8
  num_layers: 6
  dropout: 0.1
  save_dir: "models/saved"

# Training configuration
training:
  seed: 42
  epochs: 300
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 10
  log_interval: 10
  num_folds: 5

# Logging configuration
logging:
  log_dir: "logs" 